# -*- coding: utf-8 -*-
"""image processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qnLsCM8usPYlj6lJQG31Wp-0sLp-v9Hb
"""

import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import os


def calculate_psnr(img1, img2):
    arr1 = np.array(img1).astype(float)
    arr2 = np.array(img2).astype(float)

    mse = np.mean((arr1 - arr2) ** 2)

    if mse == 0:
        return 100

    return 20 * np.log10(255.0 / np.sqrt(mse))


def load_image(path):
    return Image.open(path).convert("RGB")


def show_images(images, titles, figsize=(12, 6)):
    fig, ax = plt.subplots(1, len(images), figsize=figsize)

    if len(images) == 1:
        ax = [ax]

    for i in range(len(images)):
        ax[i].imshow(images[i])
        ax[i].set_title(titles[i])
        ax[i].axis("off")

    plt.tight_layout()
    plt.show()


def run_edit(input_path, prompt, output_path):
    cmd = (
        f'python edit.py '
        f'--input_path="{input_path}" '
        f'--prompt="{prompt}" '
        f'--output_path="{output_path}"'
    )

    print(cmd)
    os.system(cmd)

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!rm -rf FaceLock
!git clone https://github.com/taco-group/FaceLock.git

!pip install transformers==4.38.2 diffusers==0.27.2 huggingface-hub==0.23.0 peft==0.9.0 accelerate==0.27.2 insightface onnxruntime-gpu opencv-python lpips

from google.colab import files
import os

print("Upload your photo:")
uploaded = files.upload()

for filename in uploaded.keys():
    os.rename(filename, "my_face.jpg")
    print("Success! File renamed to my_face.jpg")

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/FaceLock
import os
from google.colab import userdata
from PIL import Image

# Access setup
os.environ['HF_HOME'] = '/content/hf_cache'
os.environ['HUGGINGFACE_HUB_TOKEN'] = userdata.get('HF_TOKEN')
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

# Preparation (compress to 512x512)
img = Image.open("/content/my_face.jpg").convert('RGB').resize((512, 512), Image.Resampling.LANCZOS)
img.save("my_face_512.jpg")

# Run defense
!python defend.py --input_path="my_face_512.jpg" --defend_method="facelock" --attack_budget=0.08 --output_path="adv_my_face_512.png"

img_orig = load_image('my_face_512.jpg')
img_adv = load_image('adv_my_face_512.png')

show_images(
    [img_orig, img_adv],
    [
        "1. Original (my_face_512.jpg)",
        "2. Protected photo (adv_my_face_512.png)"
    ]
)

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/FaceLock

run_edit(
    "adv_my_face_512.png",
    "a professional corporate headshot, studio lighting",
    "edited_adv_face.png"
)

# 1. Load images
orig = load_image('my_face_512.jpg')
adv = load_image('adv_my_face_512.png')

# 2. Convert to numbers (arrays)
orig_arr = np.array(orig).astype(float)
adv_arr = np.array(adv).astype(float)

# 3. Subtract the original from the protected photo
# Take the absolute difference so the noise is a positive number
diff = np.abs(adv_arr - orig_arr)

# 4. Amplify the noise by 10 times to make it visible
diff_amplified = diff * 10
diff_amplified = np.clip(diff_amplified, 0, 255).astype(np.uint8)

# 5. Plot the result using the helper function
diff_amplified_img = Image.fromarray(diff_amplified)

show_images(
    [diff_amplified_img, adv],
    ["Amplified invisible noise", "How it looks on the photo"]
)

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/FaceLock

# 1. Attack parameters
my_custom_prompt = "barbie style"

# 2. Performing the attack
!python edit.py --input_path="adv_my_face_512.png" --prompt="{my_custom_prompt}" --output_path="edited_adv_face.png"

# 3. Displaying the result immediately
img_orig = load_image('my_face_512.jpg')
img_edited = load_image('edited_adv_face.png')

show_images(
    [img_orig, img_edited],
    [
        "Original (before attack)",
        f"Attack result: {my_custom_prompt}"
    ]
)

print(f"Attack completed! Prompt: {my_custom_prompt}")

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/FaceLock

my_custom_prompt = "barbie style"

# 2. Performing the attack
!python edit.py --input_path="adv_my_face_512.png" --prompt="{my_custom_prompt}" --output_path="edited_adv_face.png"

# 2. ATTACK WITHOUT PROTECTION (using original file)
!python edit.py --input_path="my_face_512.jpg" --prompt="{my_custom_prompt}" --output_path="edited_NO_protection.png"

# 3. Visualization: Original vs Result without protection vs Result with FaceLock
img_orig = load_image('my_face_512.jpg')
img_no_prot = load_image('edited_NO_protection.png')
img_with_prot = load_image('edited_adv_face.png')

show_images(
    [img_orig, img_no_prot, img_with_prot],
    [
        "Original",
        "Without FaceLock (how AI sees you)",
        "With FaceLock (protection worked)"
    ],
    figsize=(15, 5)
)

# from huggingface_hub import InferenceClient
# from google.colab import userdata
# import base64
# from io import BytesIO

# # 1. Visualization
# img_orig = load_image('my_face_512.jpg')
# img_edited = load_image('edited_adv_face.png')

# fig, ax = plt.subplots(1, 2, figsize=(12, 6))
# ax[0].imshow(img_orig); ax[0].set_title("Original (before attack)"); ax[0].axis("off")
# ax[1].imshow(img_edited); ax[1].set_title("Generation result (after FaceLock)"); ax[1].axis("off")
# plt.tight_layout()
# plt.show()

# # 2. Expert analysis (VIPGuard logic)
# def image_to_base64(img_path):
#     img = Image.open(img_path)
#     buffer = BytesIO()
#     img.save(buffer, format="JPEG")
#     return base64.b64encode(buffer.getvalue()).decode("utf-8")

# client = InferenceClient(token=userdata.get('HF_TOKEN'))
# prompt = "Analyze these two images. Compare the eyes, jaw, and nose. Is the identity of the person on the second image destroyed by FaceLock? Answer professionally."

# messages = [{
#     "role": "user",
#     "content": [
#         {"type": "text", "text": prompt},
#         {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{image_to_base64('my_face_512.jpg')}"}},
#         {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{image_to_base64('edited_adv_face.png')}"}},
#     ],
# }]

# print("\n" + "="*30)
# print("VIPGUARD EXPERT ANALYSIS REPORT")
# print("="*30 + "\n")

# response = client.chat_completion(
#     model="Qwen/Qwen2.5-VL-72B-Instruct",
#     messages=messages,
#     max_tokens=1500)

# print(response.choices[0].message.content)

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/FaceLock

# 1. First, visualization (your photos side by side)
import matplotlib.pyplot as plt
from PIL import Image

img_orig = Image.open('my_face_512.jpg')
img_edited = Image.open('edited_adv_face.png')

fig, ax = plt.subplots(1, 2, figsize=(12, 6))
ax[0].imshow(img_orig)
ax[0].set_title("Original (before attack)")
ax[0].axis("off")

ax[1].imshow(img_edited)
ax[1].set_title("Generation result (after FaceLock)")
ax[1].axis("off")
plt.tight_layout()
plt.show()

# 2. Now, expert analysis (VIPGuard-style)
from google import genai
from google.colab import userdata

client = genai.Client(api_key=userdata.get('GEMINI_API_KEY'))

prompt = """
You are a biometric security expert.
Analyze these two images. Compare the structural features of the face (eyes, cheekbones, jaw, nose).
Explain if there are differences in biometric identity.
Conclude: has the person's identity in the second photo been successfully destroyed as a result of generative editing?
"""

print("\nRunning expert analysis...\n")

response = client.models.generate_content(
    model='gemini-2.5-flash',
    contents=[prompt, img_orig, img_edited]
)

print("--- EXPERT REPORT ---")
print(response.text)

!pip install deepface
from deepface import DeepFace

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/FaceLock

my_custom_prompt = "make the person wear a glasses"

# 2. Performing the attack
!python edit.py --input_path="adv_my_face_512.png" --prompt="{my_custom_prompt}" --output_path="edited_adv_face.png"

# 2. ATTACK WITHOUT PROTECTION (using original file)
!python edit.py --input_path="my_face_512.jpg" --prompt="{my_custom_prompt}" --output_path="edited_NO_protection.png"

# 3. Visualization: Original vs Result without protection vs Result with FaceLock
img_orig = load_image('my_face_512.jpg')
img_no_prot = load_image('edited_NO_protection.png')
img_with_prot = load_image('edited_adv_face.png')

show_images(
    [img_orig, img_no_prot, img_with_prot],
    [
        "Original",
        "Without FaceLock (how AI sees you)",
        "With FaceLock (protection worked)"
    ],
    figsize=(15, 5)
)

import cv2
from insightface.app import FaceAnalysis
from scipy.spatial.distance import cosine

print("[SYSTEM]: Initializing ArcFace biometric model (InsightFace)...")
# 1. Load the face recognition model (buffalo_l contains ArcFace)
app = FaceAnalysis(name='buffalo_l', providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])
app.prepare(ctx_id=0, det_size=(640, 640)) # ctx_id=0 means using GPU

# 2. Load images (OpenCV reads them in BGR format, which is needed for InsightFace)
img_orig = cv2.imread('my_face_512.jpg')
img_edited = cv2.imread('edited_NO_protection.png')

# =========================================================
# VISUALIZATION BLOCK: Convert BGR (OpenCV) to RGB (Matplotlib)
img_orig_rgb = cv2.cvtColor(img_orig, cv2.COLOR_BGR2RGB)
img_edited_rgb = cv2.cvtColor(img_edited, cv2.COLOR_BGR2RGB)

fig, ax = plt.subplots(1, 2, figsize=(12, 6))
ax[0].imshow(img_orig_rgb)
ax[0].set_title("1. Original Image")
ax[0].axis("off")

ax[1].imshow(img_edited_rgb)
ax[1].set_title("2. Edited (NO protection)")
ax[1].axis("off")

plt.tight_layout()
plt.show() # This command will draw the images on the screen
# =========================================================

# 3. Find faces and extract biometric vectors (embeddings)
faces_orig = app.get(img_orig)
faces_edited = app.get(img_edited)

if len(faces_orig) == 0 or len(faces_edited) == 0:
    print("Error: Face not found in one of the photos!")
else:
    # Take the vector of the first detected face
    emb_orig = faces_orig[0].embedding
    emb_edited = faces_edited[0].embedding

    # 4. Calculate Cosine Distance
    # Cosine distance = 1 - Cosine Similarity
    distance = cosine(emb_orig, emb_edited)

    # Standard threshold for ArcFace model: if distance is greater than 0.68, they are different people
    threshold = 0.68
    is_same_person = distance < threshold

    # 5. Pretty print the report for the commission
    print("\n" + "="*50)
    print("FACELOCK VERIFICATION REPORT")
    print("="*50)
    print(f"Verified Identity : {is_same_person}")
    print(f"Distance          : {distance:.4f}")
    print(f"Threshold         : {threshold:.4f}")
    print(f"Model             : ArcFace")
    print(f"Metric            : cosine")
    print("="*50)

    if not is_same_person:
        print("✓ Face recognition failed.")
        print("✓ Identity protection appears successful.")
    else:
        print("⚠ Face recognition still succeeds. Protection failed.")

import cv2
import matplotlib.pyplot as plt
from insightface.app import FaceAnalysis
from scipy.spatial.distance import cosine

print("[SYSTEM]: Initializing ArcFace biometric model (InsightFace)...")
# 1. Load the face recognition model (buffalo_l contains ArcFace)
app = FaceAnalysis(name='buffalo_l', providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])
app.prepare(ctx_id=0, det_size=(640, 640)) # ctx_id=0 means using GPU

# 2. Load images (OpenCV reads them in BGR format, which is needed for InsightFace)
img_orig = cv2.imread('my_face_512.jpg')
img_edited = cv2.imread('edited_adv_face.png')

# =========================================================
# VISUALIZATION BLOCK: Convert BGR (OpenCV) to RGB (Matplotlib)
img_orig_rgb = cv2.cvtColor(img_orig, cv2.COLOR_BGR2RGB)
img_edited_rgb = cv2.cvtColor(img_edited, cv2.COLOR_BGR2RGB)

fig, ax = plt.subplots(1, 2, figsize=(12, 6))
ax[0].imshow(img_orig_rgb)
ax[0].set_title("1. Original Image")
ax[0].axis("off")

ax[1].imshow(img_edited_rgb)
ax[1].set_title("2. Edited (with FaceLock protection)")
ax[1].axis("off")

plt.tight_layout()
plt.show() # This command will draw the images on the screen
# =========================================================

# 3. Find faces and extract biometric vectors (embeddings)
faces_orig = app.get(img_orig)
faces_edited = app.get(img_edited)

if len(faces_orig) == 0 or len(faces_edited) == 0:
    print("Error: Face not found in one of the photos!")
else:
    # Take the vector of the first detected face
    emb_orig = faces_orig[0].embedding
    emb_edited = faces_edited[0].embedding

    # 4. Calculate Cosine Distance
    # Cosine distance = 1 - Cosine Similarity
    distance = cosine(emb_orig, emb_edited)

    # Standard threshold for ArcFace model: if distance is greater than 0.68, they are different people
    threshold = 0.68
    is_same_person = distance < threshold

    # 5. Pretty print the report for the commission
    print("\n" + "="*50)
    print("FACELOCK VERIFICATION REPORT")
    print("="*50)
    print(f"Verified Identity : {is_same_person}")
    print(f"Distance          : {distance:.4f}")
    print(f"Threshold         : {threshold:.4f}")
    print(f"Model             : ArcFace")
    print(f"Metric            : cosine")
    print("="*50)

    if not is_same_person:
        print("✓ Face recognition failed.")
        print("✓ Identity protection appears successful.")
    else:
        print("⚠ Face recognition still succeeds. Protection failed.")

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/FaceLock

my_custom_prompt = "make him wear glasses"

# 2. Performing the attack
!python edit.py --input_path="adv_my_face_512.png" --prompt="{my_custom_prompt}" --output_path="edited_adv_face.png"

# 2. ATTACK WITHOUT PROTECTION (using original file)
!python edit.py --input_path="my_face_512.jpg" --prompt="{my_custom_prompt}" --output_path="edited_NO_protection.png"

# 3. Visualization: Original vs Result without protection vs Result with FaceLock
img_orig = load_image('my_face_512.jpg')
img_no_prot = load_image('edited_NO_protection.png')
img_with_prot = load_image('edited_adv_face.png')

show_images(
    [img_orig, img_no_prot, img_with_prot],
    [
        "Original",
        "Without FaceLock (how AI sees you)",
        "With FaceLock (protection worked)"
    ],
    figsize=(15, 5)
)

